export const RightSide = () => {
  return (
    <div className="lg:fixed top-[90px]  overflow-y-auto  w-full h-full lg:w-[16.7%] lg:shadow-md">
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
      <h1>sadasd</h1>
    </div>
  );
};
